### ISSUE TITLE
g610 brown help required

### ISSUE THREAD

**Issue by babhijit** [MatMoul/g810-led#46] opened 2017-02-04 14:48 UTC
When I tried to set up fx effect using the command:
        g610-led -fx hwave keys ff

The entire keyboard became dark. Thanks in advance for help :)

**Comment by MatMoul** [comment] 2017-02-04 18:05
Thank for your return...

At this time, -fx is confirmed only on G810 because I don't have other model for test it.

Have you tested with other value than ff?
And for other effects? Do they work?

**Comment by MohamadSaada** [comment] 2017-02-07 18:32
Hi MatMoul, sorry for hijacking the thread, but there is no other way of contacting you, I've uploaded my code for the GUI under [LogiGSK](https://github.com/MohamadSaada/LogiGSK), if you can check whether it works on your device or not, I would really appreciate it.

**Comment by MatMoul** [comment] 2017-02-08 22:08
@MohamadSaada I will try this week-end if I found time...

**Comment by CReimer** [comment] 2017-03-11 22:32
Just to let you know.
All effects work on my g910 just fine.

**Comment by MatMoul** [comment] 2017-03-11 22:57
@CReimer Thanks for your return

**Comment by MatMoul** [comment] 2017-03-13 19:57
@babhijit I close this issue because I don't have return... but you can reply me here if you encouter problem

**Closed by MatMoul** 2017-03-13 19:57 UTC
Labels: question

**Comment by jpl81** [comment] 2017-06-29 19:39
I also have a G610. The hwave, vwave and cwave effects don't work on my g610 irrespective of the value given. The cycle effect works but the value of speed does not seem to make any difference. Other effects (color, breathing) work as they should.

**Comment by MatMoul** [comment] 2017-06-29 20:12
@jpl81 Thank for your return, but taht is an other issue...
I'm missing time thes days but open a new issue for this case.
